Shop.Web/Areas/Admin/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Application.Interfaces;
using Shop.Domain.ViewModels.Admin.Order;
using Shop.Web.Extentions;
using System.Threading.Tasks;

namespace Shop.Web.Areas.Admin.Controllers
{
    public class OrderController : AdminBaseController
    {
        #region constractor
        private readonly IOrderService _orderService;
        public OrderController(IOrderService orderService)
        {
            _orderService = orderService;
        }
        #endregion

        #region filter-orders
        public async Task<IActionResult> FilterOrders(FilterOrdersViewModel filterOrders)
        {
            return View(await _orderService.FilterOrders(filterOrders));
        }
        #endregion


        #region change order-state
        public async Task<IActionResult> ChangeStateToSent(long orderId)
        {
            var result = await _orderService.ChangeStateToSent(orderId);
            if (result)
            {
                return JsonResponseStatus.Success();
            }

            return JsonResponseStatus.Error();

        }
        #endregion

        #region orderdetail
        public async Task<IActionResult> OrderDetail(long orderId)
        {
            var data = await _orderService.GetOrderDetail(orderId);
            if (data == null)
            {
                return NotFound();
            }

            return View(data);
        }
        #endregion

    }
}

Shop.Web/Areas/Admin/Views/Order/FilterOrders.cshtml
@using Shop.Domain.ViewModels.Admin.Order
@model FilterOrdersViewModel
@{
    ViewData["Title"] = "مدیریت سفارش ها";
    int index = 1;
}
<div class="row mt-5">
    <div class="col-md-3">
        <div class="card shadow-sm">
            <div class="card-body">

                <p class="card-text">@ViewData["Title"]</p>
                <form asp-area="admin" asp-controller="Order" asp-action="FilterOrders" id="filter-Form" method="get">
                    <input asp-for="PageId" type="hidden" />
                    <div class="form-group">
                        <label>وضعیت</label>
                        <select class="form-control" asp-for="OrderStateFilter" asp-items="@Html.GetEnumSelectList<OrderStateFilter>()"></select>

                    </div>
                    <button type="submit" class="btn btn-info mt-3 mb-3 btn-block">فیلتر</button>
                </form>


            </div>
        </div>


    </div>
    <div class="col-md-9">
        @if (Model.Orders != null && Model.Orders.Any())
        {
            <div class="card shadow-sm">
                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">کاربر</th>
                                <th scope="col">پرداخت شده / نشده</th>
                                <th scope="col">مبلغ پرداخت نهایی</th>
                                <th scope="col">وضعیت</th>
                                <th scope="col">دستورات</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach (var order in Model.Orders)
                            {
                                <tr id="ajax-url-item-@order.Id">
                                    <th scope="row">@index</th>
                                    <td>
                                        @order.User.GetUserName()
                                    </td>
                                    <td>
                                        @if (order.IsFinaly)
                                        {
                                            <span class="text-success">پرداخت شده</span>
                                        }
                                        else
                                        {
                                            <span class="text-danger">پرداخت نشده</span>
                                        }
                                    </td>
                                    <td>@order.Ordersum.ToString("#,0 تومان")</td>
                                    <td>@order.OrderState.GetEnumName()</td>
                                    <td>
                                        
                                        <a class="btn btn-info btn-sm" asp-area="Admin" asp-controller="Order" asp-action="ChangeStateToSent" asp-route-orderId="@order.Id" ajax-url-button="@order.Id">ارسال</a>

                                        <a class="btn btn-warning btn-sm" asp-area="Admin" asp-controller="Order" asp-action="OrderDetail" asp-route-orderId="@order.Id">جزییات</a>
                                    </td>
                                </tr>
                                index++;
                            }
                        </tbody>
                    </table>
                </div>
            </div>

        }
        else
        {
            <div class="alert alert-danger">
                <b>ایتمی وجود ندارد</b>
            </div>
        }

        <partial name="_AdminPaging" model="Model.GetCurrentPaging()" />
    </div>
</div>

Shop.Web/Areas/Admin/Views/Order/OrderDetail.cshtml
@model Shop.Domain.Models.Orders.Order
@{
    ViewData["Title"] = "جززیات سفارش";
    int index = 1;
}

<div class="row mt-5">
    <div class="col-md-3">
        <div class="card shadow-sm">
            <div class="card-body">
                <p class="card-text">@ViewData["Title"]</p>
                <div class="form-group">
                    <label>نام درخواست کننده:</label>
                    <p>@Model.User.GetUserName()</p>

                </div>
                <div class="form-group">
                    <label>شماره تماس درخواست کننده:</label>
                    <p>@Model.User.PhoneNumber</p>

                </div>
                 <div class="form-group">
                    <label>مبلغ نهایی:</label>
                    <p>@Model.Ordersum.ToString("#,0 تومان")</p>

                </div>
            </div>
        </div>


    </div>
    <div class="col-md-9">
        @if (Model.OrderDetails != null && Model.OrderDetails.Any())
        {
            <div class="card shadow-sm">
                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">تصویر محصول</th>
                                <th scope="col">نام محصول</th>
                                <th scope="col">قیمت محصول</th>
                                <th scope="col">تعداد</th>
                                <th scope="col">قیمت کل</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach (var orderDetail in Model.OrderDetails)
                            {
                                <tr>
                                    <th scope="row">@index</th>
                                    <td>
                                        <img src="@(PathExtensions.ProductOrgin +orderDetail.Product.ProductImageName)" class="img-thumbnail" style="width:40px;">

                                    </td>
                                    <td>
                                        @orderDetail.Product.Name
                                    </td>
                                    <td>@orderDetail.Product.Price.ToString("#,0 تومان")</td>
                                    <td>@orderDetail.Count</td>
                                    @{
                                        var price = orderDetail.Price * orderDetail.Count;
                                    }

                                    <td>@price.ToString("#,0 تومان")</td>

                                </tr>
                                index++;
                            }
                        </tbody>
                    </table>
                </div>
            </div>

        }
        else
        {
            <div class="alert alert-danger">
                <b>ایتمی وجود ندارد</b>
            </div>
        }
    </div>
</div>